CarRentingSystem/CarRentingSystem/Areas/Admin/Controllers/CarController.cs
using System;
using CarRentingSystem.Core.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace CarRentingSystem.Areas.Admin.Controllers
{
	public class CarController : AdminController
	{
		private readonly ICarService carService;

        public CarController(ICarService _carService)
		{
			carService = _carService;
		}

		[HttpGet]
		public async Task<IActionResult> Approve()
		{
			var model = await carService.GetUnApprovedAsync();

			return View(model);
		}

		[HttpPost]
        public async Task<IActionResult> Approve(int carId)
        {
			await carService.ApproveCarAsync(carId);

            return RedirectToAction(nameof(Approve));
        }
    }
}

CarRentingSystem/CarRentingSystem/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CarRentingSystem.Areas.Admin.Controllers
{
    public class HomeController : AdminController
    {
        public IActionResult Board()
        {
            return View();
        }

        public IActionResult ForApproval()
        {
            return View();
        }
    }
}

CarRentingSystem/CarRentingSystem/Areas/Admin/Controllers/RentController.cs
using System;
using CarRentingSystem.Core.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace CarRentingSystem.Areas.Admin.Controllers
{
	public class RentController : AdminController
	{
		private readonly IRentService rentService;

		public RentController(IRentService _rentService)
		{
			rentService = _rentService;
		}

		public async Task<IActionResult> AllRents()
		{
			var model = await rentService.AllRentAsync();

			return View(model);
		}
	}
}

CarRentingSystem/CarRentingSystem/Areas/Admin/Controllers/UserController.cs
using System;
using CarRentingSystem.Core.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace CarRentingSystem.Areas.Admin.Controllers
{
	public class UserController : AdminController
	{
		private readonly IUserService userService;

		public UserController(IUserService _userService)
		{
			userService = _userService;
		}

		public async Task<IActionResult> All()
		{
            var model = await userService.AllAsync();

            return View(model);
		}
	}

}

CarRentingSystem/CarRentingSystem/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CarRentingSystem.Models;
using CarRentingSystem.Core.Models.Home;
using CarRentingSystem.Core.Contracts;
using Microsoft.AspNetCore.Authorization;

namespace CarRentingSystem.Controllers;

public class HomeController : BaseController
{
    private readonly ILogger<HomeController> _logger;
    private readonly ICarService carService;

    public HomeController(ILogger<HomeController> logger,
                          ICarService _carService)
    {
        _logger = logger;
        carService = _carService;
    }

    [AllowAnonymous]
    public async Task<IActionResult> Index()
    {
        var model = await carService.LastCarsAsync();

        return View(model);
    }

    [AllowAnonymous]
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error(int statusCode)
    {
        if (statusCode == 400)
        {
            return View("Error400");
        }

        if (statusCode == 401)
        {
            return View("Error401");
        }

        if (statusCode == 404)
        {
            return View("Error404");
        }
        return View();
    }
}

CarRentingSystem/CarRentingSystem/Areas/Admin/Views/Home/Board.cshtml
@{
    ViewData["Title"] = "Board";
}
<center>
    <h2>Area for administrators! :)</h2>
</center>
<div class="row">
    <div class="col-md-1">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">For Approval</h5>
                <p class="card-text">Please check new cars </p>
                <a asp-area="Admin" asp-controller="Car" asp-action="Approve" class="btn btn-primary">For Approval</a>
            </div>
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-1">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">All Cars</h5>
                <p class="card-text">Here you can see all of your cars </p>
                <a asp-area="" asp-controller="Car" asp-action="All" class="btn btn-primary">All Cars</a>
            </div>
        </div>
    </div>
</div>

<br />
<div class="row">
    <div class="col-md-2">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">All Rents</h5>
                <p class="card-text">Here you can see all rental cars </p>
                <a asp-area="Admin" asp-controller="Rent" asp-action="AllRents" class="btn btn-primary">All rental Cars</a>
            </div>
        </div>
    </div>
</div>

<br />
<div class="row">
    <div class="col-md-2">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">All Users</h5>
                <p class="card-text">Here you can see all users</p>
                <a asp-area="Admin" asp-controller="User" asp-action="All" class="btn btn-primary">All Users</a>
            </div>
        </div>
    </div>
</div>